# Uncomment to start the workflow to push the main branch
# This is a Github Actions workflow file that automates the deployment for dezoomcamp project
# name: CD
# on:
#   push:
#     branches: [main]
# jobs:
#   deploy:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Repository checkout
#         uses: actions/checkout@v2
#       - name: Connects to VPS via SSH
#         uses: appleboy/ssh-action@v0.1.3
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           port: ${{ secrets.SERVER_PORT }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           key: ${{ secrets.SERVER_KEY }}
#           passphrase: ${{ secrets.SERVER_PASSPHRASE }}
#           script: |
#             cd ${{ secrets.PROJECT_PATH }}
#             sudo git checkout main
#             sudo git pull origin main
#             python3 manage.py migrate
#             sudo systemctl restart crm-backend